기능 구현 완료(테스트 코드 포함 X)
f-lab-edu/sago pull request #2
Opened 2021-12-01 14:17 UTC by AnneMayor

2021-12-04 06:24 UTC, gksxodnd007 requested changes

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        return "회원 인증이 완료되었습니다.";
string을 직접 반환하는 것 보단 request model을 하나 만드는 건 어떨까요??
```json
{
    "data": {
        "message": "회원 인증이 완료되었습니다."
    }
}
```

이런 느낌으로 response 포맷을 맞춰주면 좋을 것 같아요. 클래스 모양은 그럼 generic을 이용하면 이런식이 나올 수 있습니다.

```java
@Getter
@RequiresArgsContructor
public class ApiResponse<T> {
    private final T data;
}

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        redisTemplate.delete(loginSecurityService.getCurrentLoginUsername().trim());
해당 기능도 UserService#logout 을 호출하는게 더 좋을 것 같아요 :) Controller에서 persistence layer 관련 객체를 직접 다루는 것은 좋지 않은 것 같아요 :)

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        if(!redisTemplate.opsForValue().getOperations().hasKey(loginSecurityService.getCurrentLoginUsername().trim())) throw new UserException("먼저 로그인 해주세요.");
1. 여기도 다시한번 고민 해보시면 좋을 것 같아요. RedisTemplate을 직접 이용하지 말고 별도의 객체로 한번 감싸면 좋을 것 같아요. 로그인 정보를 담는 datasource는 Redis일수도 있고 mysql일수도있고 memcached일 수도 있어요. 시스템은 언제든 교체될 수 있으니까요. Controller가 어떤 datasource를 사용하는지 모르게 하는게 좋아요 :)

2. JWT를 이용하는데 로그인 정보를 redis에서 관리하는 이유가 따로 있을까요?

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/dto/LoginDto.java
> +@Builder
멤버변수가 두개뿐이어서 builder를 사용할 필요는 없을 것 같아요 :)

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/service/UserService.java
> +    public String checkDuplicateId(String userId) {
트랜잭션을 사용할 필요 없을 것 같습니다. 트랜잭션은 비싼 연산이라 필요한 곳에만 사용하는 것을 권고드려요 :)

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/service/UserService.java
> +            throw new UserException("등록되지 않은 계정입니다.");
앞서 리뷰드린 ExceptionHandler를 통해 throw 하는 Exception들을 handling하면 더 좋을 것 같아요 :)

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/service/UserService.java
> +    @Transactional(rollbackFor = {java.lang.Exception.class})
rollbackFor를 이유가 무엇일까요??

2021-12-04 06:24 UTC, gksxodnd007 commented on src/main/java/com/dhmall/user/service/UserService.java
> +        SimpleMailMessage message = new SimpleMailMessage();
1. 이메일 전송은 생각보다 오래걸릴 수 있습니다. 비동기 처리되도록 하면 좋을 것 같아요 :)
2. 해당 로직은 EmailService를 별도로 만들어서 메서드로 추출하면 좋을 것 같아요

2021-12-04 06:30 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/dto/UserDto.java
> +    private Timestamp updatedAt;
Timestamp보다는 java에서 제공하는 ZoneDateTime, OffsetDateTime, LocalDateTime등을 살펴보시고 적절한 time 객체를 사용하시는게 좋을 것 같아요 :)

2021-12-04 11:12 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/service/UserService.java
> +        UserDto userFromDB = this.userMapper.findByIdAndPassword(userId, encrypedPasswd);
database에 password 비교 로직을 맡기기보다다는 `findById`를 통해 user의 정보를 읽어온 후 서버에서 password값을 비교하는게 더 좋을 것 같아요 :)

2021-12-04 11:14 UTC, f-lab-hubert commented on src/main/java/com/dhmall/util/UserUtil.java
> +        StringBuffer sb = new StringBuffer();
StringBuilder를 사용하시지 않고 StringBuffer를 사용한 이유는 뭘까요??

2021-12-04 11:15 UTC, f-lab-hubert commented on src/main/java/com/dhmall/util/UserUtil.java
> +        return sb;
StringBuffer나 StringBuilder는 String연산용으로 사용하고 값처리는 String을 사용하는게 좋을 것 같아요. `sb.toString()`을 통해 String으로 return하도록 바꾸시는게 좋을 것 같아요.

2021-12-04 11:23 UTC, f-lab-hubert commented on src/main/java/com/dhmall/util/UserUtil.java
> +        MessageDigest md = MessageDigest.getInstance("SHA-512");
전에 말씀드렸듯이 password를 암호화할땐 salt값을 추가해서 암복호화를 하시는게 좋습니다. 그리고 hash처리와 암호화 처리는 엄연히 다른 처리이기 때문에 password 암호화 하는 방법은 한번 더 고민해보시면 좋을 것 같아요. AES 알고리즘 같이 복호화가 가능한 알고리즘도 있으니 한번 살펴보시면 좋을 것 같아요. 지금 암호화처리가 틀렸다라기 보다는 다양하게 살펴보고 선택한 알고리즘인지 한번 더 생각해보시면 좋을 것 같아요.

2021-12-05 06:14 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +    @Transactional(rollbackFor = {java.lang.Exception.class})
여기 부분에서 제가 RollbackFor를 정의해준 이유가 일반적으로 Runtime 에러가 발생하면 DB에 Commit한 실행을 Rollback한다고 이해했는데요 여기 부분 로직은 Controller에서 물론 NullPointerException을 검증해주고 있으나 혹시나 모를 컴파일 에러에 대비하고자...컴파일 에러 발생 시 Rollback 해주기 위해 다음과 같이 작성해보았습니다...

2021-12-05 06:16 UTC, AnneMayor commented on src/main/java/com/dhmall/util/UserUtil.java
> +        StringBuffer sb = new StringBuffer();
StringBuffer VS StringBuilder 이 두 개의 차이점에 대해 저희 수업 시간에 다뤄봤었는데 그때 StringBuffer가 thread-safe한 API라고 알고 있어서요 물론...해당 로직부분이 병렬 처리를 필요로 하는 로직은 아니기에 StringBuilder를 활용해도 이슈가 없을 것으로 판단이 들지만 전 혹시나 싶은 마음에...Buffer 클래스를 사용하였습니다

2021-12-05 06:17 UTC, AnneMayor commented on src/main/java/com/dhmall/util/UserUtil.java
> +        MessageDigest md = MessageDigest.getInstance("SHA-512");
아 저는 그 Salt값으로 authKey값을 준건데 다르게 줄 수 있는 값이 있나보군요!한번 찾아보겠습니다~

2021-12-05 06:40 UTC, AnneMayor commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        if(!redisTemplate.opsForValue().getOperations().hasKey(loginSecurityService.getCurrentLoginUsername().trim())) throw new UserException("먼저 로그인 해주세요.");
1. 아 넵넵 알겠습니다 한번 고민해볼게욤!
2. 그 JWT에서 Refresh Token이랑 Access Token을 발행해주는데 Refresh Token 유효기간이 7일이다보니 해당 토큰을 임시저장해놓을 공간이 필요할 것으로 생각이 되더라구요 Refresh Token을 사용하는 이유는 이제 Access Token을 탈취당했을 때의 문제를 예방하고자 Access Token 주기를 짧게 하고 Refresh Token으로 발행해주는 로직을 구현한건데요 이 Refresh Token을 어떻게 관리하면 좋을지 고민해보다 Redis 캐싱 기능을 활용해야겠다고 결론이 났어요. MySQL같은 DB에 따로 저장하기에는 JWT만의 장점인 빠른 인증을 활용할 수 있을 것 같지 않아서 Redis같은 캐싱 전용 메모리를 쓰자고 생각했습니다 Redis VS Memcached 캐싱 메모리 종류에선 사실 Memcached가 제가 디자인한 소규모 서비스에는 적절한 기술인데 캐싱 메모리도 장애 대응을 위해 Master-Slave 구조를 가져가고싶어서 Redis를 선택하였습니다...

2021-12-07 15:40 UTC, f-lab-hubert commented on src/main/java/com/dhmall/util/UserUtil.java
> +        MessageDigest md = MessageDigest.getInstance("SHA-512");
보통 current time값을 주긴하는데 authKey값도 current time처럼 매번 다른 값이 주어지는 거라면 좋은 것 같습니다. :)

2021-12-07 15:58 UTC, AnneMayor commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        Optional.ofNullable(newUser)
1. 아 이게 약간 고쳐야하는 버릇 중에 하나긴한데...너무 쓸데없이 방어코드를 많이 넣는 성향이 있어가지구요...코멘트 감사합니당...ㅋ
2. 넵넵 알겠습니다 분리해서 더 깔끔하게 작성해볼게욤

2021-12-07 16:02 UTC, AnneMayor commented on src/main/java/com/dhmall/user/controller/UserController.java
> +        if(!redisTemplate.opsForValue().getOperations().hasKey(loginSecurityService.getCurrentLoginUsername().trim())) throw new UserException("먼저 로그인 해주세요.");
코멘트 주신대로 좀 더 단순한 로직으로 구현하도록 수정할게요!

2021-12-07 16:04 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +    @Transactional(rollbackFor = {java.lang.Exception.class})
코멘트 주신대로 Checked Exception 자체가 Anti-pattern이라고 하셨기에 로직을 Runtime Exception에서 잡도록 코드 단에서 수정할게요!

2021-12-07 16:05 UTC, AnneMayor commented on src/main/java/com/dhmall/util/UserUtil.java
> +        StringBuffer sb = new StringBuffer();
코멘트 주신대로 StringBuffer는 연산할 때 주로 사용하도록 할게욤 성능 상에도 차이가 있는 것으로 보이니 수정하도록 하겠습니당

2021-12-08 12:02 UTC, AnneMayor commented on src/main/java/com/dhmall/user/dto/UserDto.java
> +    private Timestamp updatedAt;
LocalDteTime 타입으로 할게욤

2021-12-08 17:15 UTC, AnneMayor commented on src/main/java/com/dhmall/user/dto/UserDto.java
> +    private Timestamp updatedAt;
그 멘토님 제가 이거 테스트했는데 그 DB 테이블 컬럼 데이터 타입도 같이 변경해줘야 하더라구요? 이거 그럼 테이블 스키마도 같이 변경해야한다는 말씀이실까요?

2021-12-09 13:35 UTC, AnneMayor commented on src/main/java/com/dhmall/user/dto/UserDto.java
> +    private Timestamp updatedAt;
코멘트 주신 거에서 ZonedDateTime API로 수정할게요

2021-12-18 08:34 UTC, f-lab-hubert requested changes
소소한 코멘트 남겨봤습니다. 코드가 많이 좋아진것 같습니다. 수고 많으셨어요!

2021-12-18 08:34 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/controller/UserController.java
> +    public UserDto info(HttpServletRequest request) {
HttpServletRequest를 직접 사용하신 이유가 있으실까요??
```java
public UserDto info(@RequestHeader(JwtFilter.AUTHORIZATION_HEADER) accessToken) {
...
}
```
이렇게 해도 되지 않을까 싶어서요 :)

2021-12-18 08:34 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/service/UserService.java
> +        newUser.setAuthKey("SNS API Key Value");
임시로 key를 발급해주는 것 보다는 null로 비워두는 것은 어떨까요??

2021-12-18 08:34 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/service/UserService.java
> +        if(user != null) throw new UserAccountException(HttpStatus.BAD_REQUEST, ErrorCode.CLIENT_ALREADY_EXISTED_ACCOUNT_ERROR, "이미 등록된 아이디입니다.");
duplicate 일 경우에는 http status code: 409가 더 적합하지 않을까 고민해봤어요 :)

2021-12-18 08:34 UTC, f-lab-hubert commented on src/main/java/com/dhmall/user/service/UserService.java
> +        loginUser.setPassword(password);
해당 코드들은 어떤 기능일까요?? 초기화해주고 쓰이는 곳이 없어서요.

2021-12-18 08:34 UTC, f-lab-hubert commented on src/test/java/com/dhmall/user/service/UserServiceTest.java
> +@ActiveProfiles("dev")
테스트 코드의 profile이 왜 dev일까요??

2021-12-22 05:42 UTC, AnneMayor commented on src/main/java/com/dhmall/user/controller/UserController.java
> +    public UserDto info(HttpServletRequest request) {
넵넵 다음 PR때 적용해서 넣을게요!

2021-12-22 05:42 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +        newUser.setAuthKey("SNS API Key Value");
넵넵 그게 더 나을 것 같네요 그렇게 바꾸도록 할게요!

2021-12-22 05:44 UTC, AnneMayor commented on src/test/java/com/dhmall/user/service/UserServiceTest.java
> +@ActiveProfiles("dev")
릴리즈 버젼의 경우 Master-Slave 형식으로 가져갈까 고민을 해봤었는데요 이번 프로젝트에서는 심플한 아키텍쳐로 가져가보겠습니다 그게 더 취지에 맞는 것으로 보여서요

2021-12-24 13:27 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +        newUser.setAuthKey("SNS API Key Value");
아예 그냥 저 로직은 삭제하는 방향으로 가져갔어요 말씀주신대로 Over engineering 하는 것 같다는 판단이 들어서요.

2021-12-24 13:28 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +        if(user != null) throw new UserAccountException(HttpStatus.BAD_REQUEST, ErrorCode.CLIENT_ALREADY_EXISTED_ACCOUNT_ERROR, "이미 등록된 아이디입니다.");
아 그 부분에 대해선 고민 안해봤는데 한번 수정해보겠습니다!

2021-12-24 13:29 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +        loginUser.setPassword(password);
이건 사실 Spring Security에서 필요한 정보를 넘기는 역할을 하는 코드인데 좀 깔끔하지 않다고 생각하고는 있었습니다 이것도 한번 수정해서 올려볼게요

2021-12-24 19:40 UTC, AnneMayor commented on src/main/java/com/dhmall/user/service/UserService.java
> +        loginUser.setPassword(password);
이 부분은 아직 고민중에 있습니다 이거 제외하고 나머지 코멘트들 확인 부탁드려요~

2021-12-26 02:25 UTC, f-lab-hubert approved these changes
요 PR도 정상적으로 동작한다면 코드리뷰는 추후에 리팩토링하셔도 좋습니다. 수고많으셨어요 :)

2021-12-27 06:55 UTC, merged