💸 실시간 온라인 경매 서비스
f-lab-edu/sago pull request #5
Opened 2021-12-18 04:24 UTC by AnneMayor

2021-12-18 08:47 UTC, f-lab-hubert requested changes

2021-12-18 08:47 UTC, f-lab-hubert commented on src/main/java/com/dhmall/auction/dto/ChatRoomDto.java
> +        sessions.parallelStream().forEach(session -> auctionService.sendMessage(session, message));
parallelStream()은 주의해서 사용하여야 하는데 왜 그런지 한번 찾아보시면 좋을 것 같아요 :)

2021-12-18 08:47 UTC, f-lab-hubert commented on src/main/java/com/dhmall/auction/dto/ChatRoomDto.java
> +            sessions.add(session);
websocket 세션을 로컬 메모리에서 관리하는 것으로 보이는데요. 다음과 같은 문제들이 있을 것 같아요.
1. 사용자가 연결을 끊어도 Collection에서 session을 제거해주는 코드가 없어서 죽은 session들이 계속해서 생겨날 것 같아요. memory leak이 발생할 것 같습니다.
2. 해당 인스턴스들을 scale out한다고 하면 서로다른 인스턴스에 접속된 유저들은 서로 통신이 불가능하여 채팅이 원할하게 동작하지 않을 것 같아요

2021-12-18 08:47 UTC, f-lab-hubert commented on src/main/java/com/dhmall/auction/handler/WebSocketHandler.java
> +        // TODO: 주기적으로 Redis 데이터, MySQL DB로 마이그레이션(Redis 데이터 삭제)[비동기]
성능을 높이기위해 채팅 정보를 redis에 먼저 저장하고 db로 동기화 시키는 걸까요?? 이렇게 된다면 db에 동기화되기 전에 장애가 발생한다면 채팅의 내용이 유실될 수도 있을 것 같아요. 캐싱관련 로직은 개발자마다 다른 생각을 갖고 있겠지만 저 같은 경우는 캐싱데이터를 db로 동기화 하는 등의 로직은 지양하고 있습니다. 데이터 유실 문제와 더불어 로직이 너무 복잡해질 수 있기 때문인데요. 캐싱은 최대한 단순하게 가는 것이 좋다고 생각되어서요. **캐싱데이터는 ttl을 걸어두어 시간이 지나면 자연스럽게 지워지도록 하고 캐시 저장소에 데이터가 없다면 다시 db에서 로드되도록 하는게 좋은데요.** 캐싱된 데이터를 수정하기 시작하면 db와의 sync가 깨졌을 때 여러문제가 발생할 수 있습니다. 요건 다른 방법을 고민해보시는게 좋을 것 같아요. 다른방법이 당장 빠르게 떠오르지 않는다면 일단 성능문제는 생각하지않고 메시지를 바로 db에 저장하는 것을 추천드려요

2021-12-22 07:14 UTC, AnneMayor commented on src/main/java/com/dhmall/auction/handler/WebSocketHandler.java
> +        // TODO: 주기적으로 Redis 데이터, MySQL DB로 마이그레이션(Redis 데이터 삭제)[비동기]
아 넵 알겠습니다 성능을 높이기 위해 적용해본건데 한번 다른 방법이 있는지 찾아보고 정 모르겠다 싶으면 일단 안정성에 초점을 두고 기능 구현을 할게요

2021-12-22 10:17 UTC, AnneMayor commented on src/main/java/com/dhmall/auction/dto/ChatRoomDto.java
> +            sessions.add(session);
넵 말씀하신 코멘트 한번 반영해볼게요

2021-12-25 07:27 UTC, AnneMayor commented on src/main/java/com/dhmall/auction/dto/ChatRoomDto.java
> +        sessions.parallelStream().forEach(session -> auctionService.sendMessage(session, message));
요건 제가 공부중에 있어서 다음 수정 때 업로드하겠습니다!

2021-12-26 02:23 UTC, f-lab-hubert approved these changes
기능이 정상적으로 동작된다면 저의 코멘트를 당장 반영하지 않아도 좋습니다. :) 수고많으셨어요!

2021-12-30 17:37 UTC, merged